
 



//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Heima8.OA.IDAL;
using Heima8.OA.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Heima8.OA.EFDAL
{


    public partial class ActionInfoDal:BaseDal<ActionInfo>,IActionInfoDal
	{

	}
    public partial class DailyWorkDal:BaseDal<DailyWork>,IDailyWorkDal
	{

	}
    public partial class OrderInfoDal:BaseDal<OrderInfo>,IOrderInfoDal
	{

	}
    public partial class R_UserInfo_ActionInfoDal:BaseDal<R_UserInfo_ActionInfo>,IR_UserInfo_ActionInfoDal
	{

	}
    public partial class RoleInfoDal:BaseDal<RoleInfo>,IRoleInfoDal
	{

	}
    public partial class SysDeptDal:BaseDal<SysDept>,ISysDeptDal
	{

	}
    public partial class UserInfoDal:BaseDal<UserInfo>,IUserInfoDal
	{

	}
    public partial class UserInfoExtDal:BaseDal<UserInfoExt>,IUserInfoExtDal
	{

	}
}






