
 



//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Heima8.OA.EFDAL;
using Heima8.OA.IDAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Heima8.OA.DALFactory
{
    public partial class DbSession:IDbSession
    {
		

				public IActionInfoDal ActionInfoDal 
		{
			get { return StaticDalFactory.GetActionInfoDal(); }
		}
				public IDailyWorkDal DailyWorkDal 
		{
			get { return StaticDalFactory.GetDailyWorkDal(); }
		}
				public IOrderInfoDal OrderInfoDal 
		{
			get { return StaticDalFactory.GetOrderInfoDal(); }
		}
				public IR_UserInfo_ActionInfoDal R_UserInfo_ActionInfoDal 
		{
			get { return StaticDalFactory.GetR_UserInfo_ActionInfoDal(); }
		}
				public IRoleInfoDal RoleInfoDal 
		{
			get { return StaticDalFactory.GetRoleInfoDal(); }
		}
				public ISysDeptDal SysDeptDal 
		{
			get { return StaticDalFactory.GetSysDeptDal(); }
		}
				public IUserInfoDal UserInfoDal 
		{
			get { return StaticDalFactory.GetUserInfoDal(); }
		}
				public IUserInfoExtDal UserInfoExtDal 
		{
			get { return StaticDalFactory.GetUserInfoExtDal(); }
		}
			}
}






