
 



//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using Heima8.OA.EFDAL;
using Heima8.OA.IDAL;
using Heima8.OA.NHDAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;

namespace Heima8.OA.DALFactory
{
    /// <summary>
    /// 由简单工厂转变成了抽象工厂
    /// 抽象工厂  VS  简单工厂
    /// </summary>
    public partial class StaticDalFactory
    {
				public static IActionInfoDal GetActionInfoDal()
		{
			return Assembly.Load(assemblyName)
				.CreateInstance(assemblyName + ".ActionInfoDal") as IActionInfoDal;
		}
				public static IDailyWorkDal GetDailyWorkDal()
		{
			return Assembly.Load(assemblyName)
				.CreateInstance(assemblyName + ".DailyWorkDal") as IDailyWorkDal;
		}
				public static IOrderInfoDal GetOrderInfoDal()
		{
			return Assembly.Load(assemblyName)
				.CreateInstance(assemblyName + ".OrderInfoDal") as IOrderInfoDal;
		}
				public static IR_UserInfo_ActionInfoDal GetR_UserInfo_ActionInfoDal()
		{
			return Assembly.Load(assemblyName)
				.CreateInstance(assemblyName + ".R_UserInfo_ActionInfoDal") as IR_UserInfo_ActionInfoDal;
		}
				public static IRoleInfoDal GetRoleInfoDal()
		{
			return Assembly.Load(assemblyName)
				.CreateInstance(assemblyName + ".RoleInfoDal") as IRoleInfoDal;
		}
				public static ISysDeptDal GetSysDeptDal()
		{
			return Assembly.Load(assemblyName)
				.CreateInstance(assemblyName + ".SysDeptDal") as ISysDeptDal;
		}
				public static IUserInfoDal GetUserInfoDal()
		{
			return Assembly.Load(assemblyName)
				.CreateInstance(assemblyName + ".UserInfoDal") as IUserInfoDal;
		}
				public static IUserInfoExtDal GetUserInfoExtDal()
		{
			return Assembly.Load(assemblyName)
				.CreateInstance(assemblyName + ".UserInfoExtDal") as IUserInfoExtDal;
		}
			}
}






