
 



//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using Heima8.OA.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Heima8.OA.IBLL
{
    public  partial interface IActionInfoService:IBaseService<ActionInfo>
	{
	}
    public  partial interface IDailyWorkService:IBaseService<DailyWork>
	{
	}
    public  partial interface IOrderInfoService:IBaseService<OrderInfo>
	{
	}
    public  partial interface IR_UserInfo_ActionInfoService:IBaseService<R_UserInfo_ActionInfo>
	{
	}
    public  partial interface IRoleInfoService:IBaseService<RoleInfo>
	{
	}
    public  partial interface ISysDeptService:IBaseService<SysDept>
	{
	}
    public  partial interface IUserInfoService:IBaseService<UserInfo>
	{
	}
    public  partial interface IUserInfoExtService:IBaseService<UserInfoExt>
	{
	}
}






