
 



//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Heima8.OA.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Heima8.OA.IDAL
{

	public partial interface IActionInfoDal:IBaseDal<ActionInfo>
	{

	}
	public partial interface IOrderInfoDal:IBaseDal<OrderInfo>
	{

	}
	public partial interface IRoleInfoDal:IBaseDal<RoleInfo>
	{

	}
	public partial interface IUserInfoDal:IBaseDal<UserInfo>
	{

	}
}






