
 



//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using Heima8.OA.EFDAL;
using Heima8.OA.IBLL;
using Heima8.OA.IDAL;
using Heima8.OA.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Heima8.OA.BLL
{
    public  partial class ActionInfoService:BaseService<ActionInfo>,IActionInfoService
	{
	}
    public  partial class DailyWorkService:BaseService<DailyWork>,IDailyWorkService
	{
	}
    public  partial class OrderInfoService:BaseService<OrderInfo>,IOrderInfoService
	{
	}
    public  partial class R_UserInfo_ActionInfoService:BaseService<R_UserInfo_ActionInfo>,IR_UserInfo_ActionInfoService
	{
	}
    public  partial class RoleInfoService:BaseService<RoleInfo>,IRoleInfoService
	{
	}
    public  partial class SysDeptService:BaseService<SysDept>,ISysDeptService
	{
	}
    public  partial class UserInfoService:BaseService<UserInfo>,IUserInfoService
	{
	}
    public  partial class UserInfoExtService:BaseService<UserInfoExt>,IUserInfoExtService
	{
	}
}






